version: '2'

services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    ports:
      - 3306:3306
    env_file: docker.env
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: on_duty
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    depends_on:
      - mysql
volumes:
  dbdata:
    driver: local
