version: '2'

services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    ports:
      - 8001:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:duty.ballfish.io"
      - "traefik.basic.port=8001"
      - "traefik.basic.protocol=http"
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    ports:
      - 3306:3306
    env_file: docker.env
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - web
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: on_duty
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    restart: always
    networks:
      - web

volumes:
  dbdata:
    driver: local

networks:
  web:
    external: true